name: unit-tests

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
   ci:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@master


         - name: Setup node env
           uses: actions/setup-node@v3
           with:
              path: backend/
              node-version: "16"
              cache: yarn

         - name: Install dependencies
           run: cd backend/ && yarn install

         - name: Run harhat unit test
           run: cd backend/ && yarn hardhat coverage

         - name: Codecov
           uses: codecov/codecov-action@v3
           with:
              path: backend/
              token: ${{ secrets.CODECOV_TOKEN }}
