name: unit-tests

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
   ci:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@v2
           with:
              path: backend/

         - name: Setup node env
           uses: actions/setup-node@v3
           with:
              node-version: "16"
              cache: yarn

         - name: Install dependencies
           run: yarn install

         - name: Run harhat unit test
           run: yarn hardhat coverage

         - name: Codecov
           uses: codecov/codecov-action@v3
           with:
              token: ${{ secrets.CODECOV_TOKEN }}
